FROM grafana/alloy:latest
COPY config.alloy /etc/alloy/config.alloy
ENTRYPOINT ["alloy", "run", "--stability.level=public-preview", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy"]